"""add smssession table

Revision ID: 89861899a4f8
Revises: 987bb000eee3
Create Date: 2026-07-09 12:09:02.836002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '89861899a4f8'
down_revision: Union[str, Sequence[str], None] = '987bb000eee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smssession',
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sa.Enum('AWAIT_NAME', 'AWAIT_COUNTY', 'AWAIT_BUSINESS', 'AWAIT_INCOME', 'AWAIT_FREQUENCY', 'COMPLETE', name='smssessionstate'), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('income', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smssession')
    # ### end Alembic commands ###
