"""make profile fields optional and slim ussdsession

Revision ID: 987bb000eee3
Revises: aec88f1d1e88
Create Date: 2026-07-08 23:02:05.535906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '987bb000eee3'
down_revision: Union[str, Sequence[str], None] = 'aec88f1d1e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ussdsession',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('national_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('claim_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_ussdsession_phone_number'), 'ussdsession', ['phone_number'], unique=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'county',
               existing_type=postgresql.ENUM('MOMBASA', 'KWALE', 'KILIFI', 'TANA_RIVER', 'LAMU', 'TAITA_TAVETA', 'GARISSA', 'WAJIR', 'MANDERA', 'MARSABIT', 'ISIOLO', 'MERU', 'THARAKA_NITHI', 'EMBU', 'KITUI', 'MACHAKOS', 'MAKUENI', 'NYANDARUA', 'NYERI', 'KIRINYAGA', 'MURANGA', 'KIAMBU', 'TURKANA', 'WEST_POKOT', 'SAMBURU', 'TRANS_NZOIA', 'UASIN_GISHU', 'ELGEYO_MARAKWET', 'NANDI', 'BARINGO', 'LAIKIPIA', 'NAKURU', 'NAROK', 'KAJIADO', 'KERICHO', 'BOMET', 'KAKAMEGA', 'VIHIGA', 'BUNGOMA', 'BUSIA', 'SIAYA', 'KISUMU', 'HOMA_BAY', 'MIGORI', 'KISII', 'NYAMIRA', 'NAIROBI', name='county'),
               nullable=True)
    op.alter_column('user', 'business_type',
               existing_type=postgresql.ENUM('MAMA_MBOGA', 'MITUMBA', 'KIBANDA_FOOD', 'SALON_BARBERSHOP', 'JUAKALI', 'ELECTRONICS_PHONE', 'SHOES_BAGS', 'DUKA', 'TAILORING', 'OTHER', name='businesstype'),
               nullable=True)
    op.alter_column('user', 'income_bracket',
               existing_type=postgresql.ENUM('BELOW_500', 'RANGE_500_1000', 'RANGE_1000_3000', 'RANGE_3000_10000', 'ABOVE_10000', name='incomebracket'),
               nullable=True)
    op.alter_column('user', 'payment_frequency',
               existing_type=postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', name='paymentfrequency'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'payment_frequency',
               existing_type=postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', name='paymentfrequency'),
               nullable=False)
    op.alter_column('user', 'income_bracket',
               existing_type=postgresql.ENUM('BELOW_500', 'RANGE_500_1000', 'RANGE_1000_3000', 'RANGE_3000_10000', 'ABOVE_10000', name='incomebracket'),
               nullable=False)
    op.alter_column('user', 'business_type',
               existing_type=postgresql.ENUM('MAMA_MBOGA', 'MITUMBA', 'KIBANDA_FOOD', 'SALON_BARBERSHOP', 'JUAKALI', 'ELECTRONICS_PHONE', 'SHOES_BAGS', 'DUKA', 'TAILORING', 'OTHER', name='businesstype'),
               nullable=False)
    op.alter_column('user', 'county',
               existing_type=postgresql.ENUM('MOMBASA', 'KWALE', 'KILIFI', 'TANA_RIVER', 'LAMU', 'TAITA_TAVETA', 'GARISSA', 'WAJIR', 'MANDERA', 'MARSABIT', 'ISIOLO', 'MERU', 'THARAKA_NITHI', 'EMBU', 'KITUI', 'MACHAKOS', 'MAKUENI', 'NYANDARUA', 'NYERI', 'KIRINYAGA', 'MURANGA', 'KIAMBU', 'TURKANA', 'WEST_POKOT', 'SAMBURU', 'TRANS_NZOIA', 'UASIN_GISHU', 'ELGEYO_MARAKWET', 'NANDI', 'BARINGO', 'LAIKIPIA', 'NAKURU', 'NAROK', 'KAJIADO', 'KERICHO', 'BOMET', 'KAKAMEGA', 'VIHIGA', 'BUNGOMA', 'BUSIA', 'SIAYA', 'KISUMU', 'HOMA_BAY', 'MIGORI', 'KISII', 'NYAMIRA', 'NAIROBI', name='county'),
               nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_ussdsession_phone_number'), table_name='ussdsession')
    op.drop_table('ussdsession')
    # ### end Alembic commands ###
