"""create initial tables

Revision ID: aec88f1d1e88
Revises: 
Create Date: 2026-07-07 21:40:52.222152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'aec88f1d1e88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('national_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_no', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_pin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('failed_pin_attempts', sa.Integer(), nullable=False),
    sa.Column('county', sa.Enum('MOMBASA', 'KWALE', 'KILIFI', 'TANA_RIVER', 'LAMU', 'TAITA_TAVETA', 'GARISSA', 'WAJIR', 'MANDERA', 'MARSABIT', 'ISIOLO', 'MERU', 'THARAKA_NITHI', 'EMBU', 'KITUI', 'MACHAKOS', 'MAKUENI', 'NYANDARUA', 'NYERI', 'KIRINYAGA', 'MURANGA', 'KIAMBU', 'TURKANA', 'WEST_POKOT', 'SAMBURU', 'TRANS_NZOIA', 'UASIN_GISHU', 'ELGEYO_MARAKWET', 'NANDI', 'BARINGO', 'LAIKIPIA', 'NAKURU', 'NAROK', 'KAJIADO', 'KERICHO', 'BOMET', 'KAKAMEGA', 'VIHIGA', 'BUNGOMA', 'BUSIA', 'SIAYA', 'KISUMU', 'HOMA_BAY', 'MIGORI', 'KISII', 'NYAMIRA', 'NAIROBI', name='county'), nullable=False),
    sa.Column('business_type', sa.Enum('MAMA_MBOGA', 'MITUMBA', 'KIBANDA_FOOD', 'SALON_BARBERSHOP', 'JUAKALI', 'ELECTRONICS_PHONE', 'SHOES_BAGS', 'DUKA', 'TAILORING', 'OTHER', name='businesstype'), nullable=False),
    sa.Column('income_bracket', sa.Enum('BELOW_500', 'RANGE_500_1000', 'RANGE_1000_3000', 'RANGE_3000_10000', 'ABOVE_10000', name='incomebracket'), nullable=False),
    sa.Column('payment_frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='paymentfrequency'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_county'), 'user', ['county'], unique=False)
    op.create_index(op.f('ix_user_national_id'), 'user', ['national_id'], unique=True)
    op.create_index(op.f('ix_user_phone_no'), 'user', ['phone_no'], unique=True)
    op.create_table('policyrecommendation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policyrecommendation_user_id'), 'policyrecommendation', ['user_id'], unique=False)
    op.create_table('smslog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='smsdirection'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smslog_direction'), 'smslog', ['direction'], unique=False)
    op.create_index(op.f('ix_smslog_user_id'), 'smslog', ['user_id'], unique=False)
    op.create_table('policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('policy_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', name='policystatus'), nullable=False),
    sa.Column('coverage_amount', sa.Float(), nullable=False),
    sa.Column('premium_amount', sa.Float(), nullable=False),
    sa.Column('premium_frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='paymentfrequency'), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['policyrecommendation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_policy_code'), 'policy', ['policy_code'], unique=True)
    op.create_index(op.f('ix_policy_status'), 'policy', ['status'], unique=False)
    op.create_index(op.f('ix_policy_user_id'), 'policy', ['user_id'], unique=False)
    op.create_table('claim',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('FIRE', 'THEFT', 'FLOOD', 'OTHER', name='claimcategory'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('claim_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'DENIED', name='claimstatus'), nullable=False),
    sa.Column('filed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_claim_code'), 'claim', ['claim_code'], unique=True)
    op.create_index(op.f('ix_claim_policy_id'), 'claim', ['policy_id'], unique=False)
    op.create_index(op.f('ix_claim_status'), 'claim', ['status'], unique=False)
    op.create_table('premiumpayment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('provider_transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premiumpayment_policy_id'), 'premiumpayment', ['policy_id'], unique=False)
    op.create_index(op.f('ix_premiumpayment_provider_transaction_id'), 'premiumpayment', ['provider_transaction_id'], unique=True)
    op.create_index(op.f('ix_premiumpayment_status'), 'premiumpayment', ['status'], unique=False)
    op.create_table('ussdsession',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('national_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('income', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('claim_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_ussdsession_phone_number'), 'ussdsession', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_premiumpayment_status'), table_name='premiumpayment')
    op.drop_index(op.f('ix_premiumpayment_provider_transaction_id'), table_name='premiumpayment')
    op.drop_index(op.f('ix_premiumpayment_policy_id'), table_name='premiumpayment')
    op.drop_table('premiumpayment')
    op.drop_index(op.f('ix_claim_status'), table_name='claim')
    op.drop_index(op.f('ix_claim_policy_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_claim_code'), table_name='claim')
    op.drop_table('claim')
    op.drop_index(op.f('ix_policy_user_id'), table_name='policy')
    op.drop_index(op.f('ix_policy_status'), table_name='policy')
    op.drop_index(op.f('ix_policy_policy_code'), table_name='policy')
    op.drop_table('policy')
    op.drop_index(op.f('ix_smslog_user_id'), table_name='smslog')
    op.drop_index(op.f('ix_smslog_direction'), table_name='smslog')
    op.drop_table('smslog')
    op.drop_index(op.f('ix_policyrecommendation_user_id'), table_name='policyrecommendation')
    op.drop_table('policyrecommendation')
    op.drop_index(op.f('ix_user_phone_no'), table_name='user')
    op.drop_index(op.f('ix_user_national_id'), table_name='user')
    op.drop_index(op.f('ix_user_county'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_ussdsession_phone_number'), table_name='ussdsession')
    op.drop_table('ussdsession')
    # ### end Alembic commands ###
