"""add profile completion fields to ussdsession

Revision ID: d0f24c76f378
Revises: 89861899a4f8
Create Date: 2026-07-09 12:54:44.238061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd0f24c76f378'
down_revision: Union[str, Sequence[str], None] = '89861899a4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ussdsession', sa.Column('selected_region', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ussdsession', sa.Column('county_page', sa.Integer(), nullable=True))
    op.add_column('ussdsession', sa.Column('selected_county', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ussdsession', sa.Column('selected_business_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ussdsession', sa.Column('selected_income_bracket', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ussdsession', sa.Column('selected_payment_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ussdsession', sa.Column('selected_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ussdsession', 'selected_full_name')
    op.drop_column('ussdsession', 'selected_payment_frequency')
    op.drop_column('ussdsession', 'selected_income_bracket')
    op.drop_column('ussdsession', 'selected_business_type')
    op.drop_column('ussdsession', 'selected_county')
    op.drop_column('ussdsession', 'county_page')
    op.drop_column('ussdsession', 'selected_region')
    # ### end Alembic commands ###
