"""add region and county_page to smssession

Revision ID: fd1311b1d568
Revises: d0f24c76f378
Create Date: 2026-07-09 15:59:27.082213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fd1311b1d568'
down_revision: Union[str, Sequence[str], None] = 'd0f24c76f378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smssession', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('smssession', sa.Column('county_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smssession', 'county_page')
    op.drop_column('smssession', 'region')
    # ### end Alembic commands ###
