# app/features/ussd/constants.py

from enum import Enum


class MenuState(str, Enum):
    MAIN = "MAIN"

    REGISTER_ID = "REGISTER_ID"
    REGISTER_NAME = "REGISTER_NAME"
    REGISTER_PIN = "REGISTER_PIN"
    REGISTER_CONFIRM_PIN = "REGISTER_CONFIRM_PIN"
    REGISTER_COUNTY = "REGISTER_COUNTY"
    REGISTER_BUSINESS = "REGISTER_BUSINESS"
    REGISTER_INCOME = "REGISTER_INCOME"
    REGISTER_FREQUENCY = "REGISTER_FREQUENCY"

    LOGIN = "LOGIN"

    DASHBOARD = "DASHBOARD"

    CLAIMS = "CLAIMS"